export const countries = [
  { code: 'NG', label: 'Nigeria', sm: '234' },
  { code: 'AD', label: 'Andorra', sm: '376' },
  {
    code: 'AE',
    label: 'United Arab Emirates',
    sm: '971',
  },
  { code: 'AF', label: 'Afghanistan', sm: '93' },
  // {
  //   code: 'AG',
  //   label: 'Antigua and Barbuda',
  //   sm: '1-268',
  // },
  {
    code: 'AG',
    label: 'Antigua and Barbuda',
    sm: '1268',
  },
  // { code: 'AI', label: 'Anguilla', sm: '1-264' },
  { code: 'AI', label: 'Anguilla', sm: '1264' },
  { code: 'AL', label: 'Albania', sm: '355' },
  { code: 'AM', label: 'Armenia', sm: '374' },
  { code: 'AO', label: 'Angola', sm: '244' },
  { code: 'AR', label: 'Argentina', sm: '54' },
  // { code: 'AS', label: 'American Samoa', sm: '1-684' },
  { code: 'AT', label: 'Austria', sm: '43' },
  {
    code: 'AU',
    label: 'Australia',
    sm: '61',
    suggested: true,
  },
  { code: 'AW', label: 'Aruba', sm: '297' },
  // { code: 'AX', label: 'Alland Islands', sm: '358' },
  { code: 'AZ', label: 'Azerbaijan', sm: '994' },
  {
    code: 'BA',
    label: 'Bosnia and Herzegovina',
    sm: '387',
  },
  // { code: 'BB', label: 'Barbados', sm: '1-246' },
  { code: 'BB', label: 'Barbados', sm: '1246' },
  { code: 'BD', label: 'Bangladesh', sm: '880' },
  { code: 'BE', label: 'Belgium', sm: '32' },
  { code: 'BF', label: 'Burkina Faso', sm: '226' },
  { code: 'BG', label: 'Bulgaria', sm: '359' },
  { code: 'BH', label: 'Bahrain', sm: '973' },
  { code: 'BI', label: 'Burundi', sm: '257' },
  { code: 'BJ', label: 'Benin', sm: '229' },
  // { code: 'BL', label: 'Saint Barthelemy', sm: '590' },
  // { code: 'BM', label: 'Bermuda', sm: '1-441' },
  { code: 'BM', label: 'Bermuda', sm: '1441' },
  // { code: 'BN', label: 'Brunei Darussalam', sm: '673' },
  { code: 'BO', label: 'Bolivia', sm: '591' },
  { code: 'BR', label: 'Brazil', sm: '55' },
  // { code: 'BS', label: 'Bahamas', sm: '1-242' },
  { code: 'BS', label: 'Bahamas', sm: '1242' },
  // { code: 'BT', label: 'Bhutan', sm: '975' },
  // { code: 'BV', label: 'Bouvet Island', sm: '47' },
  { code: 'BW', label: 'Botswana', sm: '267' },
  { code: 'BY', label: 'Belarus', sm: '375' },
  { code: 'BZ', label: 'Belize', sm: '501' },
  {
    code: 'CA',
    label: 'Canada',
    sm: '1',
    suggested: true,
  },
  {
    code: 'CD',
    label: 'Congo, Democratic Republic of the',
    sm: '243',
  },
  {
    code: 'CG',
    label: 'Congo, Republic of the',
    sm: '242',
  },
  { code: 'CH', label: 'Switzerland', sm: '41' },
  { code: 'CI', label: "Cote d'Ivoire", sm: '225' },
  { code: 'CK', label: 'Cook Islands', sm: '682' },
  { code: 'CL', label: 'Chile', sm: '56' },
  { code: 'CM', label: 'Cameroon', sm: '237' },
  { code: 'CN', label: 'China', sm: '86' },
  { code: 'CO', label: 'Colombia', sm: '57' },
  { code: 'CR', label: 'Costa Rica', sm: '506' },
  { code: 'CU', label: 'Cuba', sm: '53' },
  { code: 'CV', label: 'Cape Verde', sm: '238' },
  { code: 'CW', label: 'Curacao', sm: '599' },
  { code: 'CX', label: 'Christmas Island', sm: '61' },
  { code: 'CY', label: 'Cyprus', sm: '357' },
  { code: 'CZ', label: 'Czech Republic', sm: '420' },
  {
    code: 'DE',
    label: 'Germany',
    sm: '49',
    suggested: true,
  },
  { code: 'DJ', label: 'Djibouti', sm: '253' },
  { code: 'DK', label: 'Denmark', sm: '45' },
  // { code: 'DM', label: 'Dominica', sm: '1-767' },
  { code: 'DM', label: 'Dominica', sm: '1767' },
  // {
  //   code: 'DO',
  //   label: 'Dominican Republic',
  //   sm: '1-809',
  // },
  {
    code: 'DO',
    label: 'Dominican Republic',
    sm: '1809',
  },
  { code: 'DZ', label: 'Algeria', sm: '213' },
  { code: 'EC', label: 'Ecuador', sm: '593' },
  { code: 'EE', label: 'Estonia', sm: '372' },
  { code: 'EG', label: 'Egypt', sm: '20' },
  { code: 'EH', label: 'Western Sahara', sm: '212' },
  { code: 'ER', label: 'Eritrea', sm: '291' },
  { code: 'ES', label: 'Spain', sm: '34' },
  { code: 'ET', label: 'Ethiopia', sm: '251' },
  { code: 'FI', label: 'Finland', sm: '358' },
  { code: 'FJ', label: 'Fiji', sm: '679' },
  {
    code: 'FK',
    label: 'Falkland Islands (Malvinas)',
    sm: '500',
  },
  {
    code: 'FM',
    label: 'Micronesia, Federated States of',
    sm: '691',
  },
  { code: 'FO', label: 'Faroe Islands', sm: '298' },
  {
    code: 'FR',
    label: 'France',
    sm: '33',
    suggested: true,
  },
  { code: 'GA', label: 'Gabon', sm: '241' },
  { code: 'GB', label: 'United Kingdom', sm: '44' },
  // { code: 'GD', label: 'Grenada', sm: '1-473' },
  { code: 'GD', label: 'Grenada', sm: '1473' },
  { code: 'GE', label: 'Georgia', sm: '995' },
  { code: 'GF', label: 'French Guiana', sm: '594' },
  { code: 'GG', label: 'Guernsey', sm: '44' },
  { code: 'GH', label: 'Ghana', sm: '233' },
  { code: 'GI', label: 'Gibraltar', sm: '350' },
  { code: 'GL', label: 'Greenland', sm: '299' },
  { code: 'GM', label: 'Gambia', sm: '220' },
  { code: 'GN', label: 'Guinea', sm: '224' },
  { code: 'GP', label: 'Guadeloupe', sm: '590' },
  { code: 'GQ', label: 'Equatorial Guinea', sm: '240' },
  { code: 'GR', label: 'Greece', sm: '30' },
  {
    code: 'GS',
    label: 'South Georgia and the South Sandwich Islands',
    sm: '500',
  },
  { code: 'GT', label: 'Guatemala', sm: '502' },
  // { code: 'GU', label: 'Guam', sm: '1-671' },
  { code: 'GU', label: 'Guam', sm: '1671' },
  { code: 'GW', label: 'Guinea-Bissau', sm: '245' },
  { code: 'GY', label: 'Guyana', sm: '592' },
  { code: 'HK', label: 'Hong Kong', sm: '852' },
  {
    code: 'HM',
    label: 'Heard Island and McDonald Islands',
    sm: '672',
  },
  { code: 'HN', label: 'Honduras', sm: '504' },
  { code: 'HR', label: 'Croatia', sm: '385' },
  { code: 'HT', label: 'Haiti', sm: '509' },
  { code: 'HU', label: 'Hungary', sm: '36' },
  { code: 'ID', label: 'Indonesia', sm: '62' },
  { code: 'IE', label: 'Ireland', sm: '353' },
  { code: 'IL', label: 'Israel', sm: '972' },
  { code: 'IM', label: 'Isle of Man', sm: '44' },
  { code: 'IN', label: 'India', sm: '91' },
  {
    code: 'IO',
    label: 'British Indian Ocean Territory',
    sm: '246',
  },
  { code: 'IQ', label: 'Iraq', sm: '964' },
  {
    code: 'IR',
    label: 'Iran, Islamic Republic of',
    sm: '98',
  },
  { code: 'IS', label: 'Iceland', sm: '354' },
  { code: 'IT', label: 'Italy', sm: '39' },
  { code: 'JE', label: 'Jersey', sm: '44' },
  // { code: 'JM', label: 'Jamaica', sm: '1-876' },
  { code: 'JM', label: 'Jamaica', sm: '1876' },
  { code: 'JO', label: 'Jordan', sm: '962' },
  {
    code: 'JP',
    label: 'Japan',
    sm: '81',
    suggested: true,
  },
  { code: 'KE', label: 'Kenya', sm: '254' },
  { code: 'KG', label: 'Kyrgyzstan', sm: '996' },
  { code: 'KH', label: 'Cambodia', sm: '855' },
  { code: 'KI', label: 'Kiribati', sm: '686' },
  { code: 'KM', label: 'Comoros', sm: '269' },
  // {
  //   code: 'KN',
  //   label: 'Saint Kitts and Nevis',
  //   sm: '1-869',
  // },
  {
    code: 'KN',
    label: 'Saint Kitts and Nevis',
    sm: '1869',
  },
  {
    code: 'KP',
    label: "Korea, Democratic People's Republic of",
    sm: '850',
  },
  { code: 'KR', label: 'Korea, Republic of', sm: '82' },
  { code: 'KW', label: 'Kuwait', sm: '965' },
  // { code: 'KY', label: 'Cayman Islands', sm: '1-345' },
  { code: 'KY', label: 'Cayman Islands', sm: '1345' },
  { code: 'KZ', label: 'Kazakhstan', sm: '7' },
  {
    code: 'LA',
    label: "Lao People's Democratic Republic",
    sm: '856',
  },
  { code: 'LB', label: 'Lebanon', sm: '961' },
  // { code: 'LC', label: 'Saint Lucia', sm: '1-758' },
  { code: 'LC', label: 'Saint Lucia', sm: '1758' },
  { code: 'LI', label: 'Liechtenstein', sm: '423' },
  { code: 'LK', label: 'Sri Lanka', sm: '94' },
  { code: 'LR', label: 'Liberia', sm: '231' },
  { code: 'LS', label: 'Lesotho', sm: '266' },
  { code: 'LT', label: 'Lithuania', sm: '370' },
  { code: 'LU', label: 'Luxembourg', sm: '352' },
  { code: 'LV', label: 'Latvia', sm: '371' },
  { code: 'LY', label: 'Libya', sm: '218' },
  { code: 'MA', label: 'Morocco', sm: '212' },
  { code: 'MC', label: 'Monaco', sm: '377' },
  {
    code: 'MD',
    label: 'Moldova, Republic of',
    sm: '373',
  },
  { code: 'ME', label: 'Montenegro', sm: '382' },
  {
    code: 'MF',
    label: 'Saint Martin (French part)',
    sm: '590',
  },
  { code: 'MG', label: 'Madagascar', sm: '261' },
  { code: 'MH', label: 'Marshall Islands', sm: '692' },
  {
    code: 'MK',
    label: 'Macedonia, the Former Yugoslav Republic of',
    sm: '389',
  },
  { code: 'ML', label: 'Mali', sm: '223' },
  { code: 'MM', label: 'Myanmar', sm: '95' },
  { code: 'MN', label: 'Mongolia', sm: '976' },
  { code: 'MO', label: 'Macao', sm: '853' },
  // {
  //   code: 'MP',
  //   label: 'Northern Mariana Islands',
  //   sm: '1-670',
  // },
  {
    code: 'MP',
    label: 'Northern Mariana Islands',
    sm: '1670',
  },
  { code: 'MQ', label: 'Martinique', sm: '596' },
  { code: 'MR', label: 'Mauritania', sm: '222' },
  // { code: 'MS', label: 'Montserrat', sm: '1-664' },
  { code: 'MS', label: 'Montserrat', sm: '1664' },
  { code: 'MT', label: 'Malta', sm: '356' },
  { code: 'MU', label: 'Mauritius', sm: '230' },
  { code: 'MV', label: 'Maldives', sm: '960' },
  { code: 'MW', label: 'Malawi', sm: '265' },
  { code: 'MX', label: 'Mexico', sm: '52' },
  { code: 'MY', label: 'Malaysia', sm: '60' },
  { code: 'MZ', label: 'Mozambique', sm: '258' },
  { code: 'NA', label: 'Namibia', sm: '264' },
  { code: 'NC', label: 'New Caledonia', sm: '687' },
  { code: 'NE', label: 'Niger', sm: '227' },
  // { code: 'NG', label: 'Nigeria', sm: '234' },
  { code: 'NF', label: 'Norfolk Island', sm: '672' },
  { code: 'NI', label: 'Nicaragua', sm: '505' },
  { code: 'NL', label: 'Netherlands', sm: '31' },
  { code: 'NO', label: 'Norway', sm: '47' },
  { code: 'NP', label: 'Nepal', sm: '977' },
  { code: 'NR', label: 'Nauru', sm: '674' },
  { code: 'NU', label: 'Niue', sm: '683' },
  { code: 'NZ', label: 'New Zealand', sm: '64' },
  { code: 'OM', label: 'Oman', sm: '968' },
  { code: 'PA', label: 'Panama', sm: '507' },
  { code: 'PE', label: 'Peru', sm: '51' },
  { code: 'PF', label: 'French Polynesia', sm: '689' },
  { code: 'PG', label: 'Papua New Guinea', sm: '675' },
  { code: 'PH', label: 'Philippines', sm: '63' },
  { code: 'PK', label: 'Pakistan', sm: '92' },
  { code: 'PL', label: 'Poland', sm: '48' },
  {
    code: 'PM',
    label: 'Saint Pierre and Miquelon',
    sm: '508',
  },
  { code: 'PN', label: 'Pitcairn', sm: '870' },
  { code: 'PR', label: 'Puerto Rico', sm: '1' },
  {
    code: 'PS',
    label: 'Palestine, State of',
    sm: '970',
  },
  { code: 'PT', label: 'Portugal', sm: '351' },
  { code: 'PW', label: 'Palau', sm: '680' },
  { code: 'PY', label: 'Paraguay', sm: '595' },
  { code: 'QA', label: 'Qatar', sm: '974' },
  { code: 'RE', label: 'Reunion', sm: '262' },
  { code: 'RO', label: 'Romania', sm: '40' },
  { code: 'RS', label: 'Serbia', sm: '381' },
  { code: 'RU', label: 'Russia', sm: '7' },
  { code: 'RW', label: 'Rwanda', sm: '250' },
  { code: 'SA', label: 'Saudi Arabia', sm: '966' },
  { code: 'SB', label: 'Solomon Islands', sm: '677' },
  { code: 'SC', label: 'Seychelles', sm: '248' },
  { code: 'SD', label: 'Sudan', sm: '249' },
  { code: 'SE', label: 'Sweden', sm: '46' },
  { code: 'SG', label: 'Singapore', sm: '65' },
  { code: 'SH', label: 'Saint Helena', sm: '290' },
  { code: 'SI', label: 'Slovenia', sm: '386' },
  {
    code: 'SJ',
    label: 'Svalbard and Jan Mayen',
    sm: '47',
  },
  { code: 'SK', label: 'Slovakia', sm: '421' },
  { code: 'SL', label: 'Sierra Leone', sm: '232' },
  { code: 'SM', label: 'San Marino', sm: '378' },
  { code: 'SN', label: 'Senegal', sm: '221' },
  { code: 'SO', label: 'Somalia', sm: '252' },
  { code: 'SR', label: 'Suriname', sm: '597' },
  { code: 'SS', label: 'South Sudan', sm: '211' },
  {
    code: 'ST',
    label: 'Sao Tome and Principe',
    sm: '239',
  },
  { code: 'SV', label: 'El Salvador', sm: '503' },
  // {
  //   code: 'SX',
  //   label: 'Sint Maarten (Dutch part)',
  //   sm: '1-721',
  // },
  {
    code: 'SX',
    label: 'Sint Maarten (Dutch part)',
    sm: '1721',
  },
  {
    code: 'SY',
    label: 'Syrian Arab Republic',
    sm: '963',
  },
  { code: 'SZ', label: 'Swaziland', sm: '268' },
  // {
  //   code: 'TC',
  //   label: 'Turks and Caicos Islands',
  //   sm: '1-649',
  // },
  {
    code: 'TC',
    label: 'Turks and Caicos Islands',
    sm: '1649',
  },
  { code: 'TD', label: 'Chad', sm: '235' },
  {
    code: 'TF',
    label: 'French Southern Territories',
    sm: '262',
  },
  { code: 'TG', label: 'Togo', sm: '228' },
  { code: 'TH', label: 'Thailand', sm: '66' },
  { code: 'TJ', label: 'Tajikistan', sm: '992' },
  { code: 'TK', label: 'Tokelau', sm: '690' },
  { code: 'TL', label: 'Timor-Leste', sm: '670' },
  { code: 'TM', label: 'Turkmenistan', sm: '993' },
  { code: 'TN', label: 'Tunisia', sm: '216' },
  { code: 'TO', label: 'Tonga', sm: '676' },
  { code: 'TR', label: 'Turkey', sm: '90' },
  // {
  //   code: 'TT',
  //   label: 'Trinidad and Tobago',
  //   sm: '1-868',
  // },
  {
    code: 'TT',
    label: 'Trinidad and Tobago',
    sm: '1868',
  },
  { code: 'TV', label: 'Tuvalu', sm: '688' },
  {
    code: 'TW',
    label: 'Taiwan, Province of China',
    sm: '886',
  },
  {
    code: 'TZ',
    label: 'United Republic of Tanzania',
    sm: '255',
  },
  { code: 'UA', label: 'Ukraine', sm: '380' },
  { code: 'UG', label: 'Uganda', sm: '256' },
  {
    code: 'US',
    label: 'United States',
    sm: '1',
    suggested: true,
  },
  { code: 'UY', label: 'Uruguay', sm: '598' },
  { code: 'UZ', label: 'Uzbekistan', sm: '998' },
  {
    code: 'VA',
    label: 'Holy See (Vatican City State)',
    sm: '379',
  },
  // {
  //   code: 'VC',
  //   label: 'Saint Vincent and the Grenadines',
  //   sm: '1-784',
  // },
  {
    code: 'VC',
    label: 'Saint Vincent and the Grenadines',
    sm: '1784',
  },
  { code: 'VE', label: 'Venezuela', sm: '58' },
  // {
  //   code: 'VG',
  //   label: 'British Virgin Islands',
  //   sm: '1-284',
  // },
  {
    code: 'VG',
    label: 'British Virgin Islands',
    sm: '1284',
  },
  // {
  //   code: 'VI',
  //   label: 'US Virgin Islands',
  //   sm: '1-340',
  // },
  {
    code: 'VI',
    label: 'US Virgin Islands',
    sm: '1340',
  },
  { code: 'VN', label: 'Vietnam', sm: '84' },
  { code: 'VU', label: 'Vanuatu', sm: '678' },
  { code: 'WF', label: 'Wallis and Futuna', sm: '681' },
  { code: 'WS', label: 'Samoa', sm: '685' },
  { code: 'XK', label: 'Kosovo', sm: '383' },
  { code: 'YE', label: 'Yemen', sm: '967' },
  { code: 'YT', label: 'Mayotte', sm: '262' },
  { code: 'ZA', label: 'South Africa', sm: '27' },
  { code: 'ZM', label: 'Zambia', sm: '260' },
  { code: 'ZW', label: 'Zimbabwe', sm: '263' },
]
